### ISSUE TITLE
video card / driver combo doesn't support necessary features

### ISSUE THREAD

**Issue by Brandoskey** [techcoder20/RPIDoom3Installer#2]
After installing from pi-apps and attempting to run the game I get this error

This is on a fresh install of rasbian with everything updated

> ----- Initializing OpenGL -----
> 
> Initializing OpenGL subsystem
> Using 8 color bits, 24 depth, 8 stencil display
> OpenGL vendor: Broadcom
> OpenGL renderer: V3D 4.2
> OpenGL version: OpenGL ES 3.1 Mesa 19.3.2
> X..GL_ARB_multitexture not found
> X..GL_ARB_texture_env_combine not found
> X..GL_ARB_texture_cube_map not found
> X..GL_ARB_texture_env_dot3 not found
> X..GL_ARB_texture_env_add not found
> X..GL_ARB_texture_non_power_of_two not found
> X..GL_ARB_texture_compression not found
> X..GL_EXT_texture_filter_anisotropic not found
> X..GL_EXT_texture_lod not found
> X..GL_1.4_texture_lod_bias not found
> X..GL_EXT_shared_texture_palette not found
> X..GL_EXT_texture3D not found
> X..GL_EXT_stencil_wrap not found
> X..GL_EXT_stencil_two_side not found
> ... don't have GL2.0+ glStencilOpSeparate()
> X..GL_ARB_vertex_buffer_object not found
> X..GL_ARB_vertex_program not found
> X..GL_ARB_fragment_program not found
> TODO: Sys_SetClipboardData
> ********************
> ERROR: The current video card / driver combination does not support the necessary features.
> ********************
> Sys_Error: Error during initialization
> shutdown terminal support
> Looks like dhewm3 1.5.1rc2 crashed with signal SIGSEGV (11) - sorry!
> 
> Backtrace:
>   ./dhewm3() [0x1da5e8]
>   /lib/arm-linux-gnueabihf/libc.so.6(__default_sa_restorer+0) [0xb6953120]
>   ./dhewm3() [0x24d36c]
>   ./dhewm3() [0xed0dc]
> 
> Segmentation fault

Cross posted this over on the pi-apps repo

**Comment by chills340** [comment]
If you did sudo apt upgrade on rpi os it infact downgraded your mesa version to 19.3. a simple fix to get twisters version 20.3 is to go to twisteros.com and in the faq run the mesa.run file you will find at the bottom of that page.

**Comment by Brandoskey** [comment]
Tried that, it appears to error out quickly after starting but blanks the terminal window before I can read the error and I can't locate any log. I've been trying to update meson manually but seem to stall out with this error

> Invalid version of dependency, need 'libdrm_nouveau' ['>=2.4.102'] found '2.4.100'

**Comment by chills340** [comment]
Glxinfo -B should tell you what mesa version your on. Guessing this is what you need from backports for installing mesa manually like your doing. https://packages.debian.org/bullseye/libdrm-nouveau2 download armhf one and dpkg-i filename.deb to install.

**Comment by Brandoskey** [comment]
After a lot of failures, I finally got 20.3.3 installed and I get the same error related to video card/drivers

**Comment by techcoder20** [comment]
It is working now. Still not sure about what was broken.
